// <auto-generated />
namespace ServiceDesk.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Creating_link_between_the_ticket_and_the_department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creating_link_between_the_ticket_and_the_department));
        
        string IMigrationMetadata.Id
        {
            get { return "202011151517535_Creating_link_between_the_ticket_and_the_department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
