// <auto-generated />
namespace ServiceDesk.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Сreating_communication_between_employee_and_department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Сreating_communication_between_employee_and_department));
        
        string IMigrationMetadata.Id
        {
            get { return "202011151520160_Сreating_communication_between_employee_and_department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
